# Generated by Django 5.1.1 on 2024-10-11 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habit', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('school', 'Escuela'), ('work', 'Trabajo'), ('sports', 'Deporte'), ('cleaning', 'Limpieza'), ('leisure', 'Ocio'), ('other', 'Otro')], max_length=255)),
                ('frequency', models.CharField(choices=[('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly')], max_length=1)),
                ('start_date', models.DateField()),
                ('goal', models.IntegerField()),
                ('achieved', models.IntegerField(default=0)),
                ('is_required_reminder', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
