# Generated by Django 5.1.1 on 2024-10-16 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_frequency_habitprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitprogress',
            old_name='date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='habitprogress',
            name='progress',
        ),
        migrations.AddField(
            model_name='habitprogress',
            name='completed_arrty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='habitprogress',
            name='progress_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
