# Generated by Django 5.1.1 on 2024-10-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_rename_date_habitprogress_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitprogress',
            old_name='completed_arrty',
            new_name='completed_array',
        ),
    ]
