# Generated by Django 5.1.1 on 2024-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_rename_completed_arrty_habitprogress_completed_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitprogress',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
