# Generated by Django 5.1.1 on 2024-10-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_remove_habitprogress_is_completed_habit_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitprogress',
            name='completed_array',
        ),
    ]
