# Generated by Django 5.1.1 on 2024-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_remove_habitprogress_completed_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days_elapsed',
            field=models.IntegerField(default=0),
        ),
    ]
