# Generated by Django 5.1.1 on 2024-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_habit_days_elapsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='days_elapsed',
            field=models.IntegerField(default=1),
        ),
    ]
