# Generated by Django 5.1.1 on 2024-10-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_alter_habit_days_elapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
